- .gitignore
- dist/pure.js
- dist/terminal.esm.js
- dist/terminal.js
- yarn.lock
checking in built files to dogfood until we publish
> checking in dist until we start publishing

- .eslintrc.yaml
hooking prettier into eslint, still leaving the diff and write targets as we'll use prettier on markdown files which I don't really want to install eslint plugins for
r? @jil-stripe 
CI passes, 🚢
> let eslint flag prettier

- types/terminal-js/ixmodel/app/model/com/goindex/proto/rabbit/api/jackrabbitservice.model.d.ts
- types/terminal-js/rabbit/ix-jack-rabbit-rpc.service.d.ts
- types/terminal-js/rabbit/ix-jack-rabbit.service.d.ts
- types/terminal-js/rabbit/terminal.d.ts
Added new types related to new method `ResumeCollectPayment`
The method is private so we don't need to update the API documentation.
> Update type as we added extended transactions in the SDK

- .gitattributes
- tests/types/index.ts
- types/terminal-js/ixmodel/app/model/com/goindex/proto/rabbit/api/jackrabbitservice.model.d.ts
- types/terminal-js/rabbit/discovery-client.d.ts
- types/terminal-js/rabbit/discovery.service.d.ts
- types/terminal-js/rabbit/ix-jack-rabbit-rpc.service.d.ts
- types/terminal-js/rabbit/ix-jack-rabbit.service.d.ts
- types/terminal-js/rabbit/jack-rabbit-connection-mgr.d.ts
- types/terminal-js/rabbit/terminal.d.ts
Latest type gen, updates `Reader` to have a proper status type and removes features rolled back from prod
r? @jingyu-stripe @jil-stripe @corin-stripe 
CI passes, 🚢
> merging latest types

- types/terminal.d.ts
Made a minor spelling correction in a comment.
I read the comment and then cross-referenced it with my knowledge of the English language.
> Fixed minor spelling error in comment

- types/terminal.d.ts
Pulls down the latest reader types and adds them to our public repo
CI passes, 🚢
> updating reader type

- package.json
- yarn.lock
What it says on the tin
CI passes, 🚢
> updating ws to satisfy a security ticket

- .github/ISSUE_TEMPLATE.md
> updating issue template to direct users to new live chat source

- .circleci/config.yml
- .travis.yml
What it says on the tin, migrating us from travis to circleCI
Ran the existing CI target in circleCI… works 🎉
https://app.circleci.com/pipelines/github/stripe/terminal-js/1/workflows/bdcc12b2-f72e-4da7-b7f3-9f799daa7a28/jobs/1
> adding circleci integration

- .yarnrc
- package.json
Project needs a `.yarnrc` file pointed at the public repo in order to be able to pull down a validate the most recent TSC when publishing locally
Ran locally, works, but needs to be merged and on a clean master to publish
> Add .yarnrc

- types/terminal.d.ts
Adds another field to the `options` object in `collectPaymentMethod` to allow for skipping tipping.
> Update terminal.d.ts with skip_tipping config type

- types/proto.d.ts
- types/terminal.d.ts
Adds in types for update PI feature
> Adding types for update PI feature

- package.json
> bump package.json version to 11.1

- types/terminal.d.ts
This PR adds types and methods used for collect inputs. I had to tweak the types to use interfaces instead of classes since that isn't allowed in declaration files
I copied the types I created here to webpos. I was able to make collect inputs requests and see results like normal.
> [Collect Inputs] Update collect inputs

- types/terminal.d.ts
Use `ICancelResponse` instead of {} as a type
> [Collect Inputs] Use ICancelResponse

- types/terminal.d.ts
- missed linter run in previous PR
> [v0.19.0] run linter for terminal.d.ts

- types/terminal.d.ts
What it says on the tin. All SDK methods might return an error
> Add ErrorResponse to set/get reader settings response

- types/terminal.d.ts
> prettier -w types/terminal.d.ts

- types/terminal.d.ts
- Add types for new `print` method
- Ensure `yarn ci` succeeds locally
> Add Print Types

- types/proto.d.ts
add paypay sdk models for JS
r?  @henryx-stripe
> [JS]add support for paypay
